export const START_POST_FETCHING = 'START_POST_FETCHING';
export const STOP_POST_FETCHING = 'STOP_POST_FETCHING';

export const CALL_GET_POSTS = 'CALL_GET_POSTS';
export const CALL_GET_POST_SUCCESS = 'CALL_GET_POST_SUCCESS';
export const CALL_GET_POST_FAILURE = 'CALL_GET_POST_FAILURE';